<Project>
    <PropertyGroup>
        <ValheimGamePath>C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath>$(ValheimGamePath)\BepInEx</BepInExPath>
        <CorlibPath>$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
        <PublicizedAssembliesPath>$(ValheimGamePath)\valheim_Data\Managed\publicized_assemblies</PublicizedAssembliesPath>
        <CopyOutputDLLPath>$(ValheimGamePath)\BepInEx\plugins</CopyOutputDLLPath>
        <CopyOutputDLLPath2>C:\Users\crypt\AppData\Roaming\com.kesomannen.gale\valheim\profiles\OnePointOhTesting\BepInEx\plugins\Azumatt-AzuExtendedPlayerInventory</CopyOutputDLLPath2>
        <!--<CopyOutputDLLPath3>$(ValheimGamePath)\BepInEx\plugins</CopyOutputDLLPath3>-->
        <AfterTargets>ILRepacker</AfterTargets>
    </PropertyGroup>
</Project>
