global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using BepInEx;
global using BepInEx.Bootstrap;
global using BepInEx.Configuration;
global using HarmonyLib;
global using JetBrains.Annotations;
global using TMPro;
global using UnityEngine;
global using UnityEngine.EventSystems;
global using UnityEngine.UI;
global using Object = UnityEngine.Object;
global using static AzuExtendedPlayerInventory.AzuExtendedPlayerInventoryPlugin;